# Site settings
title: 奈良で開催している子ども達のためのプログラミング道場 - CoderDojo奈良・CoderDojo生駒 -
email: nara.jp@coderdojo.com
description: > # this means to ignore newlines until "baseurl:"
  CoderDojo奈良・CoderDojo生駒:奈良で開催する子どもたちのためのコーディング道場です。
  CoderDojoとは、プログラミングやWeb製作などの創作活動に関心のある子どもたちと、
  サポートする大人や学生さんが一緒に活動するコミュニティです。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://coderdojo-nara-ikoma.github.io/" # the base hostname & protocol for your site
twitter_username: coderdojo.nara
github_username:  coderdojo-nara-ikoma

# Build settings
markdown: kramdown
