name: CI Build Jekyll
on:
  pull_request:
permissions:
  contents: read
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
